config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_for :admins

  authenticated :admin do
    root 'background/homes#home', as: :authenticated_root
  end

  get 'investments/index'

  get 'investments/edit'

  get 'investments/show'

  get 'investments/destroy'

  root 'static_pages#home'

  resources :users
  resources :loans
  resources :investments
  resources :contacts

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'full_index' => 'loans#full_index'
  get 'search_loan' => 'loans#search'
  post 'search_loan' => 'loans#search'
  get 'add_money' => 'users#add_money'
  post 'pay' => 'users#pay'
  get 'pay' => 'users#pay'
  get 'return_loan' => 'users#return_loan'
  get 'return_pay' => 'users#return_pay'
  post 'return_pay' => 'users#return_pay'

  namespace :background do
    root 'homes#home'
    resources :checks
    resources :manage_loans
    resources :manage_investments
    resources :manage_users
    resources :manage_accounts
    resources :manage_contacts

    get 'search_user' => 'manage_users#search_user'
    post 'search_user' => 'manage_users#search_user'

    get 'high_search_user' => 'manage_users#search'
    post 'high_search_user' => 'manage_users#search'

    get 'high_search_loan' => 'manage_loans#search'
    post 'high_search_loan' => 'manage_loans#search'

    get 'high_search_loan_full' => 'manage_loans#search_full'
    post 'high_search_loan_full' => 'manage_loans#search_full'

    get 'loan_index_full' => 'manage_loans#index_full'

    get 'high_search_investment' => 'manage_investments#search'
    post 'high_search_investment' => 'manage_investments#search'

    get 'high_search_account' => 'manage_accounts#search'
    post 'high_search_account' => 'manage_accounts#search'

    patch 'reject_loan' => 'manage_loans#reject_loan'
    get 'reject_loan' => 'manage_loans#reject_loan'
  end

  get 'account_info' => 'users#account_info'

  get 'show_user' => 'loans#show_user'

  get 'update_head' => 'users#update_head'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  # 主页
  def home
  end

  # 关于
  def about
    @contact = Contact.new
  end

  # 联系我们
  def contact
  end

  # 帮助
  def help
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, '关于') %>

<%= render 'shared/message' %>

<h2>公司简介</h2>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <p><%= ('X' * 80 + "\n") * 10 %></p>
  </div>
</div>



<div class="row">
  <div class="col-md-5">
    <h2>公司地址</h2>
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3447.411963832258!2d120.03884031481117!3d30.225326516960482!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x344b7b08d154046d%3A0x6ae8e0800706f5d6!2z5rWZ5rGf5bel5Lia5aSn5a2m5bGP5bOw5qCh5Yy6LeWbvuS5pummhg!5e0!3m2!1szh-CN!2sus!4v1465536317846" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
  <div class="col-md-5 col-md-offset-2">
    <h2>联系我们</h2>
    <%= form_for @contact do |f| %>
        <div class="form-group">
          <%= f.label :email, 'email' %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :name, '姓名' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :title, '主题' %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :message, '反馈内容' %>
          <%= f.text_area :message, class: 'form-control' %>
        </div>

        <%= f.submit '提交', class: 'btn btn-default pull-right' %>
    <% end %>
  </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, '帮助') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, '主页') %>

<%= render 'shared/message' %>

<!--图片轮播-->
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    <li data-target="#carousel-example-generic" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% 4.times do |index| %>
        <div class="item <%= 'active' if index == 0 %>">
          <%= image_tag "heading#{index}.jpg" %>
        </div>
    <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">上一张</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">下一张</span>
  </a>
</div>

<!--新手专享-->
<h3>新手专享</h3>
<div class="row home-row">

  <div class="col-md-2">
    <%= image_tag 'new_user1.png', class: 'new-user-image' %>
  </div>

  <div class="col-md-2 new-user-introduce">
    <p class="new-user-h4">财神道</p>
    <p class="expect-year">预期年化</p>
    <p class="percent">10%</p>
  </div>

  <div class="col-md-4 new-user-introduce">
    <p class="new-user-h4">30天尝鲜10%预期年化收益</p>
    <p class="expect-year">期限</p>
    <p class="percent">30天</p>
  </div>

  <div class="col-md-2">

  </div>

  <div class="col-md-2">
    <%= link_to '立即抢购', loans_path, type: 'button', class: 'btn btn-danger buy-now' %>
  </div>

</div>

<div class="row home-row">

  <div class="col-md-2">
    <%= image_tag 'new_user2.png', class: 'new-user-image' %>
  </div>

  <div class="col-md-2 new-user-introduce">
    <p class="new-user-h4">财神道</p>
    <p class="expect-year">预期年化</p>
    <p class="percent">10%</p>
  </div>

  <div class="col-md-4 new-user-introduce">
    <p class="new-user-h4">我出本金你赚收益,体验投资乐趣</p>
    <p class="expect-year">期限</p>
    <p class="percent">3天</p>
  </div>

  <div class="col-md-2">

  </div>

  <div class="col-md-2">
    <%= link_to '立即抢购', loans_path, type: 'button', class: 'btn btn-danger buy-now' %>
  </div>

</div>

<h3>推荐产品</h3>
<div class="row home-row">
  <div class="col-md-4">
    <%= image_tag 'product_car.png', class: 'product-image' %>
    <!--<p>培训贷款</p>-->
    <p><%= link_to '培训贷款', new_loan_path, class: 'btn btn-success' %></p>
  </div>

  <div class="col-md-4">
    <%= image_tag 'product_edu.png', class: 'product-image' %>
    <!--<p>车贷</p>-->
    <p><%= link_to '车贷', new_loan_path, class: 'btn btn-info' %></p>
  </div>

  <div class="col-md-4">
    <%= image_tag 'product_elec.png', class: 'product-image' %>
    <!--<p>数码消费贷款</p>-->
    <p><%= link_to '数码消费贷款', new_loan_path, class: 'btn btn-warning' %></p>
  </div>
</div>

<h3>产品预告</h3>
<div class="row home-row">
  <div class="col-md-3 coming-soon">
    <p>
      即将<br/>
      发布
    </p>
    <%= image_tag 'product_preview.png', class: 'product-preview-image' %>
  </div>
  <div class="col-md-9 please-wait">
    <p>敬请期待......</p>
  </div>
</div>

<h3>网站数据统计</h3>
<div class="row home-row">
  <div class="col-md-12">
    <%= image_tag 'graph1.png', class: 'data-graph' %>
    <%= image_tag 'graph2.png', class: 'data-graph' %>
  </div>
</div>