config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_for :admins

  authenticated :admin do
    root 'background/homes#home', as: :authenticated_root
  end

  get 'investments/index'

  get 'investments/edit'

  get 'investments/show'

  get 'investments/destroy'

  root 'static_pages#home'

  resources :users
  resources :loans
  resources :investments
  resources :contacts

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'full_index' => 'loans#full_index'
  get 'search_loan' => 'loans#search'
  post 'search_loan' => 'loans#search'
  get 'add_money' => 'users#add_money'
  post 'pay' => 'users#pay'
  get 'pay' => 'users#pay'
  get 'return_loan' => 'users#return_loan'
  get 'return_pay' => 'users#return_pay'
  post 'return_pay' => 'users#return_pay'

  namespace :background do
    root 'homes#home'
    resources :checks
    resources :manage_loans
    resources :manage_investments
    resources :manage_users
    resources :manage_accounts
    resources :manage_contacts

    get 'search_user' => 'manage_users#search_user'
    post 'search_user' => 'manage_users#search_user'

    get 'high_search_user' => 'manage_users#search'
    post 'high_search_user' => 'manage_users#search'

    get 'high_search_loan' => 'manage_loans#search'
    post 'high_search_loan' => 'manage_loans#search'

    get 'high_search_loan_full' => 'manage_loans#search_full'
    post 'high_search_loan_full' => 'manage_loans#search_full'

    get 'loan_index_full' => 'manage_loans#index_full'

    get 'high_search_investment' => 'manage_investments#search'
    post 'high_search_investment' => 'manage_investments#search'

    get 'high_search_account' => 'manage_accounts#search'
    post 'high_search_account' => 'manage_accounts#search'

    patch 'reject_loan' => 'manage_loans#reject_loan'
    get 'reject_loan' => 'manage_loans#reject_loan'
  end

  get 'account_info' => 'users#account_info'

  get 'show_user' => 'loans#show_user'

  get 'update_head' => 'users#update_head'

end

app/controllers/background/application_controller.rb
module Background
  class ApplicationController < ::ApplicationController
    layout 'admin_lte_2'

    before_action :authenticate_admin!
  end
end

app/controllers/background/checks_controller.rb
module Background
  class ChecksController < Background::ApplicationController
    def index
      @loans = Loan.all
    end
  end
end

app/controllers/background/homes_controller.rb
module Background
  class HomesController < Background::ApplicationController
    # 后台管理页面的主页
    def home
      # 绘制图表数据
      # 月份
      @month_data = []
      @users = []
      @loans = []
      @investments = []

      6.times do |index|
        @month_data[index] = get_month_ago(index)
        @users[index] = User.where('created_at > ? and created_at < ?', Time.parse("#{@month_data[index].year}-#{@month_data[index].month}-1"), Time.parse("#{@month_data[index].year}-#{@month_data[index].next_month.month}-1"))
        @loans[index] = Loan.where('created_at > ? and created_at < ?', Time.parse("#{@month_data[index].year}-#{@month_data[index].month}-1"), Time.parse("#{@month_data[index].year}-#{@month_data[index].next_month.month}-1"))
        @investments[index] = Investment.where('created_at > ? and created_at < ?', Time.parse("#{@month_data[index].year}-#{@month_data[index].month}-1"), Time.parse("#{@month_data[index].year}-#{@month_data[index].next_month.month}-1"))
      end

      @types = {}
      @types[:school] = Loan.where("use = '学费'").count
      @types[:car] = Loan.where("use = '车贷'").count
      @types[:elec] = Loan.where("use = '数码贷款'").count
      @types[:others] = Loan.count - @types[:school] - @types[:car] - @types[:elec]

      @month_data.reverse!
      @users.reverse!
      @loans.reverse!

      @data = {}
      # @data[:mount] = []
      # @loans.each do |loan|
      #   total = 0
      #   loan.each do |n|
      #     total += n.mount
      #   end
      #   @data[:mount] << total
      # end
      # @data[:loan_mount] = @loans.map { |n| eval(n.map {|a| a.mount}.join('+'))}.map! {|n| n.nil? ? 0 : n}
      @data[:loan_mount] = @loans.map { |n| n.map {|a| a.mount}.inject(:+)}.map! {|n| n.nil? ? 0 : n}
      # @data[:mount].map! {|n| n = n.nil? ? 0 : n}
      # puts "data[:mount] = #{@data[:mount]}"
      @data[:month] = @month_data.map { |n| "#{n.month}月" }
      @data[:users] = @users.map { |n| n.size }
      @data[:loans] = @loans.map { |n| n.size }
      @data[:investments] = @investments.map {|n| n.size}
      @data[:investment_mount] = @investments.map {|n| n.map { |a| a.mount}.inject(:+)}.map! {|n| n.nil? ? 0 : n}

      @data[:types] = @types
    end


    private

    def get_month_ago(mount)
      time = Time.now
      mount.times do
        time = time.last_month
      end
      time
      # (Time.now.month - 1 - mount) % 12 + 1
    end
  end
end

app/controllers/background/manage_accounts_controller.rb
module Background
  class ManageAccountsController < Background::ApplicationController
    def index
      @accounts = Account.order(created_at: :desc).paginate(page: params[:page], per_page: 20)
    end

    def search
      search_text = params[:account][:search_text]
      search_time = params[:account][:search_time]
      @search = Account.search do
        fulltext search_text do
          phrase_fields :user_name => 3.0
          query_phrase_slop 100
        end

        case search_time
          when '一周内'
            with(:created_at).greater_than 1.week.ago
          when '两周内'
            with(:created_at).greater_than 2.weeks.ago
          when '一个月内'
            with(:created_at).greater_than 1.month.ago
          when '三个月内'
            with(:created_at).greater_than 3.months.ago
          when '三个月以上'
            with(:created_at).less_than 3.months.ago
          else
            # 不限
            # type code here
        end
      end
    end
  end
end

app/controllers/background/manage_contacts_controller.rb
module Background
  class ManageContactsController < Background::ApplicationController
    def index
      @contacts = Contact.order(created_at: :asc).paginate(page: params[:page], per_page: 20)
    end
  end
end

app/controllers/background/manage_investments_controller.rb
module Background
  class ManageInvestmentsController < Background::ApplicationController
    def index
      @investments = Investment.all.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    end

    def search
      @search = Investment.search do
        search_mount = params[:investment][:search_mount]
        search_text = params[:investment][:search_text]

        fulltext search_text do
          query_phrase_slop 100
        end

        if search_mount == '1000以下'
          with(:mount).less_than(1000.0)
        elsif search_mount == '1000到3000'
          with(:mount, 1000...3000)
        elsif search_mount == '3000到8000'
          with(:mount, 3000...8000)
        elsif search_mount == '8000以上'
          with(:mount).greater_than(8000.0)
        end
      end
    end
  end
end

app/controllers/background/manage_loans_controller.rb
module Background
  class ManageLoansController < Background::ApplicationController
    # 查看前先验证管理员是否登录
    before_action :authenticate_admin!

    # 列出所有的待审核的项目的信息
    def index
      @loans = Loan.where("passed = 'no'").order(created_at: :desc).paginate(page: params[:page], per_page: 10)
    end

    # 列出待审核项目的详细信息
    # 项目详细信息, 申请人详细信息, 担保人详细信息
    # 带有同意或拒绝项目的功能
    def show
      @loan = Loan.find_by(id: params[:id])
      @investment = Investment.new
    end

    # 审核通过 => 更新数据库信息 + 审核通过的提示信息
    def update
      @loan = Loan.find_by(id: params[:loan][:loan_id])
      if @loan.update_attributes(passed: 'yes')
        @loan.investments do |investment|
          investment.user.profit_not_yet += investment.mount * 1.1
          investment.user.frozen_capital -= investment.mount
          investment.user.save
        end

        # 通知已经审核更新成功了
        flash.now[:success] = '审核通过'
      end
      # redrect_to background_manage_loan_url
      render 'show'
    end

    def reject_loan
      @loan = Loan.find_by(id: params[:loan][:loan_id])
      if @loan.update_attributes(passed: 'failed')
        @loan.investments do |investment|
          investment.user.fronzen_capital -= investment.mount
          investment.user.valid_capital += investment.mount
          investment.user.save
        end
        flash.now[:danger] = '审核不通过'
      end
      # redirect_to background_manage_loan_url
      render 'show'
    end

    def search_loan

    end

    def search
      time_hash = {一周内: 1.week.ago, 两周内: 2.weeks.ago, 一个月内: 1.month.ago, 三个月内: 3.months.ago}

      search_text = params[:loan][:search_text]
      search_mount = params[:loan][:search_mount]
      search_use = params[:loan][:search_use]
      search_period = params[:loan][:search_period]
      search_time = params[:loan][:search_time]

      @search = Loan.search do
        fulltext search_text do
          query_phrase_slop 100
        end

        if search_time == '三个月以上'
          with(:created_at).less_than 3.months.ago
        elsif search_time != '不限'
          with(:created_at).greater_than time_hash[:"#{search_time}"]
        end

        # (search_time == '三个月以上') ?
        #     with(:created_at).less_than 3.months.ago :
        #     with(:created_at).greater_than time_hash[:"#{search_time}"] if search_time != '不限'

        if search_mount == '1000以下'
          with(:mount).less_than(1000.0)
        elsif search_mount == '1000到3000'
          with(:mount, 1000...3000)
        elsif search_mount == '3000到8000'
          with(:mount, 3000...8000)
        elsif search_mount == '8000以上'
          with(:mount).greater_than(8000.0)
        end

        (search_use == '其他') ? without(:use, %w(学费 车贷 数码贷款)) : with(:use, "#{search_use}") if search_use != '不限'

        case search_period
          when '3个月内'
            with(:period, 0...3)
          when '3到6个月'
            with(:period, 3...6)
          when '6到12个月'
            with(:period, 6..12)
          when '1年以上'
            with(:period).greater_than(12)
          else
            # type code here
        end

        with(:passed, 'no')

        paginate page: params[:page], per_page: 10
      end
    end

    # 列出所有的满标项目
    def index_full
      @loans = Loan.where('mount = already_mount').order(updated_at: :desc).paginate(page: params[:page], per_page: 10)
    end

    # 查看满标项目的信息
    # 主要是项目的详细信息, 申请人详细信息, 担保人详细信息, 投资人详细信息
    # 显示项目的投资记录和还款情况
    def show_full
    end

    # 高级搜索
    def search_full
      time_hash = {一周内: 1.week.ago, 两周内: 2.weeks.ago, 一个月内: 1.month.ago, 三个月内: 3.months.ago}

      search_text = params[:loan][:search_text]
      search_mount = params[:loan][:search_mount]
      search_use = params[:loan][:search_use]
      search_period = params[:loan][:search_period]
      search_time = params[:loan][:search_time]

      @search = Loan.search do
        fulltext search_text do
          query_phrase_slop 100
        end

        if search_time == '三个月以上'
          with(:created_at).less_than 3.months.ago
        elsif search_time != '不限'
          with(:created_at).greater_than time_hash[:"#{search_time}"]
        end

        # (search_time == '三个月以上') ?
        #     with(:created_at).less_than 3.months.ago :
        #     with(:created_at).greater_than time_hash[:"#{search_time}"] if search_time != '不限'

        if search_mount == '1000以下'
          with(:mount).less_than(1000.0)
        elsif search_mount == '1000到3000'
          with(:mount, 1000...3000)
        elsif search_mount == '3000到8000'
          with(:mount, 3000...8000)
        elsif search_mount == '8000以上'
          with(:mount).greater_than(8000.0)
        end

        (search_use == '其他') ? without(:use, %w(学费 车贷 数码贷款)) : with(:use, "#{search_use}") if search_use != '不限'

        case search_period
          when '3个月内'
            with(:period, 0...3)
          when '3到6个月'
            with(:period, 3...6)
          when '6到12个月'
            with(:period, 6..12)
          when '1年以上'
            with(:period).greater_than(12)
          else
            # type code here
        end

        with(:passed, 'yes')
        with(:fulled, true)
        # with(:already_mount, :mount)


        paginate page: params[:page], per_page: 10
      end
    end

    # private
    #
    # def search_help(passed)
    #   time_hash = {一周内: 1.week.ago, 两周内: 2.weeks.ago, 一个月内: 1.month.ago, 三个月内: 3.months.ago}
    #
    #   search_text = params[:loan][:search_text]
    #   search_mount = params[:loan][:search_mount]
    #   search_use = params[:loan][:search_use]
    #   search_period = params[:loan][:search_period]
    #   search_time = params[:loan][:search_time]
    #
    #   @search = Loan.search do
    #     fulltext search_text do
    #       query_phrase_slop 100
    #     end
    #
    #     if search_time == '三个月以上'
    #       with(:created_at).less_than 3.months.ago
    #     elsif search_time != '不限'
    #       with(:created_at).greater_than time_hash[:"#{search_time}"]
    #     end
    #
    #     # (search_time == '三个月以上') ?
    #     #     with(:created_at).less_than 3.months.ago :
    #     #     with(:created_at).greater_than time_hash[:"#{search_time}"] if search_time != '不限'
    #
    #     if search_mount == '1000以下'
    #       with(:mount).less_than(1000.0)
    #     elsif search_mount == '1000到3000'
    #       with(:mount, 1000...3000)
    #     elsif search_mount == '3000到8000'
    #       with(:mount, 3000...8000)
    #     elsif search_mount == '8000以上'
    #       with(:mount).greater_than(8000.0)
    #     end
    #
    #     (search_use == '其他') ? without(:use, %w(学费 车贷 数码贷款)) : with(:use, "#{search_use}") if search_use != '不限'
    #
    #     case search_period
    #       when '3个月内'
    #         with(:period, 0...3)
    #       when '3到6个月'
    #         with(:period, 3...6)
    #       when '6到12个月'
    #         with(:period, 6..12)
    #       when '1年以上'
    #         with(:period).greater_than(12)
    #       else
    #         # type code here
    #     end
    #
    #     with(:passed, passed)
    #
    #     paginate page: params[:page], per_page: 10
    #   end
    # end
  end
end

app/controllers/background/manage_users_controller.rb
module Background
  class ManageUsersController < Background::ApplicationController
    def index
      @users = User.paginate(page: params[:page], per_page: 10)
    end

    def show
      @user = User.find_by(id: params[:id])
      @city = ''
      unless @user.last_sign_in_ip.nil?
        ip_info = GeoIP.new('lib/GeoLiteCity.dat').city(@user.last_sign_in_ip)
        unless ip_info.nil?
          city_hash = ip_info.to_hash
          @city = city_hash[:city_name]
        end
      end
      puts "@user.name = #{@user.name}"
    end

    # 简单搜索
    def search_user
      @search = User.search do
        fulltext params[:user][:search_text] do
          phrase_fields :name => 2.0
          phrase_fields :phone_number => 1.0
          query_phrase_slop 5
        end
        paginate :page => params[:page], :per_page => 10
      end

      # @results = User.where(id: search.results.map(&:id)).paginate(page: params[:page], per_page: 10)
      # @results = @search.results
    end

    # 高级搜索
    def search
      time_hash = {一周内: 1.week.ago, 两周内: 2.weeks.ago, 一个月内: 1.month.ago, 三个月内: 3.months.ago}

      @search = User.search do
        fulltext params[:user][:search_text] do
          phrase_fields :name => 3.0
          query_phrase_slop 100
        end

        unless params[:user][:search_time] == '不限'
          with(:created_at).greater_than(time_hash[:"#{params[:user][:search_time]}"])
        end

        unless params[:user][:search_sex] == '不限'
          with(:sex, params[:user][:search_sex])
        end

        paginate :page => params[:page], :per_page => 10
      end
    end
  end
end

app/helpers/background/checks_helper.rb
module Background::ChecksHelper
end

app/helpers/background/homes_helper.rb
module Background::HomesHelper
end

app/helpers/background/manage_accounts_helper.rb
module Background::ManageAccountsHelper
end

app/helpers/background/manage_contacts_helper.rb
module Background::ManageContactsHelper
end

app/helpers/background/manage_investments_helper.rb
module Background::ManageInvestmentsHelper
end

app/helpers/background/manage_loans_helper.rb
module Background::ManageLoansHelper
end

app/helpers/background/manage_users_helper.rb
module Background::ManageUsersHelper
end

app/views/background/manage_loans/_loan_full_search_high.html.erb
<div class="container">
  <div class="row">
    <div id="filter-panel" class="collapse filter-panel">
      <div class="panel panel-default">
        <div class="panel-body">
          <!--<form class="form-inline" role="form">-->
          <%= form_for [:background, :manage, Loan.new], url: background_high_search_loan_full_path, method: :post, html: {class: 'form-inline'} do |f| %>
              <div class="form-group">
                <label class="filter-col" style="margin-right:0;" for="pref-perpage">借款金额</label>
                <%= f.select :search_mount, %w(不限 1000以下 1000到3000 3000到8000 8000以上), {}, {class: 'form-control'} %>
                <!--<select id="pref-perpage" class="form-control">-->
                <!--<option selected="selected" value="不限">不限</option>-->
                <!--<option value="男">男</option>-->
                <!--<option value="女">女</option>-->
                <!--</select>-->
              </div> <!-- form group [rows] -->
              <div class="form-group">
                <label class="filter-col" style="margin-right:0;" for="pref-orderby">借款时间</label>
                <%= f.select :search_time, %w(不限 一周内 两周内 一个月内 三个月内 三个月以上), {}, {class: 'form-control'} %>
                <!--<select id="pref-orderby" class="form-control">-->
                <!--<option selected="selected">一周内</option>-->
                <!--<option>两周内</option>-->
                <!--<option value="">一个月内</option>-->
                <!--</select>-->
              </div> <!-- form group [order by] -->
              <div class="form-group">
                <label class="filter-col" style="margin-right:0;" for="pref-orderby">借款用途</label>
                <%= f.select :search_use, %w(不限 学费 车贷 数码贷款 其他), {}, {class: 'form-control'} %>
                <!--<select id="pref-orderby" class="form-control">-->
                <!--<option selected="selected">一周内</option>-->
                <!--<option>两周内</option>-->
                <!--<option value="">一个月内</option>-->
                <!--</select>-->
              </div> <!-- form group [order by] -->
              <div class="form-group">
                <label class="filter-col" style="margin-right:0;" for="pref-orderby">还款周期</label>
                <%= f.select :search_period, %w(不限 3个月内 3到6个月 6到12个月 1年以上), {}, {class: 'form-control'} %>
                <!--<select id="pref-orderby" class="form-control">-->
                <!--<option selected="selected">一周内</option>-->
                <!--<option>两周内</option>-->
                <!--<option value="">一个月内</option>-->
                <!--</select>-->
              </div> <!-- form group [order by] -->
              <div class="form-group">
                <label class="filter-col" style="margin-right:0;" for="pref-search">搜索:</label>
                <%= f.text_field :search_text, class: 'form-control input-sm' %>
                <!--<input type="text" class="form-control input-sm" id="pref-search">-->
              </div><!-- form group [search] -->

              <div class="form-group">
                <!--<div class="checkbox" style="margin-left:10px; margin-right:10px;">-->
                <!--<label><input type="checkbox"> Ingested</label>-->
                <!--</div>-->
                <!--<div class="checkbox" style="margin-left:10px; margin-right:10px;">-->
                <!--<label><input type="checkbox"> Automated</label>-->
                <!--</div>-->
                <!--<button type="submit" class="btn btn-default filter-col">-->
                <!--<span class="glyphicon glyphicon-record"></span> Save Settings-->
                <!--</button>-->
                <%= f.submit '搜索', class: 'btn btn-default' %>
              </div>
              <!--</form>-->
          <% end %>
        </div>
      </div>
    </div>

    <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#filter-panel">
      <span class="glyphicon glyphicon-cog"></span> 高级搜索
    </button>
  </div>
</div>

app/views/background/manage_loans/_loan_search_high.html.erb
<div class="container">
  <div class="row">
    <div id="filter-panel" class="collapse filter-panel">
      <div class="panel panel-default">
        <div class="panel-body">
          <!--<form class="form-inline" role="form">-->
          <%= form_for [:background, :manage, Loan.new], url: background_high_search_loan_path, method: :post, html: {class: 'form-inline'} do |f| %>
              <div class="form-group">
                <label class="filter-col" style="margin-right:0;" for="pref-perpage">借款金额</label>
                <%= f.select :search_mount, %w(不限 1000以下 1000到3000 3000到8000 8000以上), {}, {class: 'form-control'} %>
                <!--<select id="pref-perpage" class="form-control">-->
                <!--<option selected="selected" value="不限">不限</option>-->
                <!--<option value="男">男</option>-->
                <!--<option value="女">女</option>-->
                <!--</select>-->
              </div> <!-- form group [rows] -->
              <div class="form-group">
                <label class="filter-col" style="margin-right:0;" for="pref-orderby">借款时间</label>
                <%= f.select :search_time, %w(不限 一周内 两周内 一个月内 三个月内 三个月以上), {}, {class: 'form-control'} %>
                <!--<select id="pref-orderby" class="form-control">-->
                <!--<option selected="selected">一周内</option>-->
                <!--<option>两周内</option>-->
                <!--<option value="">一个月内</option>-->
                <!--</select>-->
              </div> <!-- form group [order by] -->
              <div class="form-group">
                <label class="filter-col" style="margin-right:0;" for="pref-orderby">借款用途</label>
                <%= f.select :search_use, %w(不限 学费 车贷 数码贷款 其他), {}, {class: 'form-control'} %>
                <!--<select id="pref-orderby" class="form-control">-->
                <!--<option selected="selected">一周内</option>-->
                <!--<option>两周内</option>-->
                <!--<option value="">一个月内</option>-->
                <!--</select>-->
              </div> <!-- form group [order by] -->
              <div class="form-group">
                <label class="filter-col" style="margin-right:0;" for="pref-orderby">还款周期</label>
                <%= f.select :search_period, %w(不限 3个月内 3到6个月 6到12个月 1年以上), {}, {class: 'form-control'} %>
                <!--<select id="pref-orderby" class="form-control">-->
                <!--<option selected="selected">一周内</option>-->
                <!--<option>两周内</option>-->
                <!--<option value="">一个月内</option>-->
                <!--</select>-->
              </div> <!-- form group [order by] -->
              <div class="form-group">
                <label class="filter-col" style="margin-right:0;" for="pref-search">搜索:</label>
                <%= f.text_field :search_text, class: 'form-control input-sm' %>
                <!--<input type="text" class="form-control input-sm" id="pref-search">-->
              </div><!-- form group [search] -->

              <div class="form-group">
                <!--<div class="checkbox" style="margin-left:10px; margin-right:10px;">-->
                <!--<label><input type="checkbox"> Ingested</label>-->
                <!--</div>-->
                <!--<div class="checkbox" style="margin-left:10px; margin-right:10px;">-->
                <!--<label><input type="checkbox"> Automated</label>-->
                <!--</div>-->
                <!--<button type="submit" class="btn btn-default filter-col">-->
                <!--<span class="glyphicon glyphicon-record"></span> Save Settings-->
                <!--</button>-->
                <%= f.submit '搜索', class: 'btn btn-default' %>
              </div>
              <!--</form>-->
          <% end %>
        </div>
      </div>
    </div>

    <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#filter-panel">
      <span class="glyphicon glyphicon-cog"></span> 高级搜索
    </button>
  </div>
</div>

app/views/background/manage_loans/index.html.erb
<%= render 'loan_search_high' %>

<br><br>

<% @loans.each do |loan| %>
    <div class="row">
      <div class="col-md-12">
        <ul class="timeline">

          <!-- timeline time label -->
          <li class="time-label">
            <span class="bg-red">
              <% time = loan.created_at %>
              <%= "#{time.year}年 #{time.month}月 #{time.day}日" %>
            </span>
          </li>
          <!-- /.timeline-label -->

          <!-- timeline item -->
          <li>
            <!-- timeline icon -->
            <i class="fa fa-user bg-blue"></i>
            <div class="timeline-item">
              <span class="time"><i class="fa fa-clock-o"></i> <%= "#{time.hour}:#{time.min}" %></span>

              <h3 class="timeline-header"><a href="#">借款申请 </a> <%= loan.use %></h3>

              <div class="timeline-body">
                <div class="row">
                  <div class="col-md-3">
                    <%= image_tag loan.user.avatar.url(:medium), class: 'head-image' %>
                  </div>
                  <div class="col-md-3">
                    <div class="box box-success box-solid loan-index-box-height">
                      <div class="box-header with-border">
                        <h3 class="box-title">个人信息</h3>

                        <!--<div class="box-tools pull-right">-->
                          <!--<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>-->
                        <!--</div>-->
                        <!-- /.box-tools -->
                      </div>
                      <!-- /.box-header -->
                      <div class="box-body">
                        email: <%= loan.user.email %><br>
                        姓名: <%= loan.user.name %><br>
                        性别: <%= loan.user.sex %><br>
                        联系电话: <%= loan.user.phone_number %>
                      </div>
                      <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                  </div>
                  <div class="col-md-3">
                    <div class="box box-warning box-solid loan-index-box-height">
                      <div class="box-header with-border">
                        <h3 class="box-title">借款信息</h3>

                        <!--<div class="box-tools pull-right">-->
                          <!--<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>-->
                          <!--</button>-->
                        <!--</div>-->
                        <!-- /.box-tools -->
                      </div>
                      <!-- /.box-header -->
                      <div class="box-body">
                        申请金额: <%= loan.mount %><br>
                        用途: <%= loan.use %><br>
                        还款方式: <%= loan.way %><br>
                        还款周期: <%= loan.period %>
                      </div>
                      <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                  </div>
                  <div class="col-md-3">
                    <div class="box box-danger box-solid loan-index-box-height">
                      <div class="box-header with-border">
                        <h3 class="box-title">工作情况</h3>

                        <!--<div class="box-tools pull-right">-->
                          <!--<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>-->
                          <!--</button>-->
                        <!--</div>-->
                        <!-- /.box-tools -->
                      </div>
                      <!-- /.box-header -->
                      <div class="box-body">
                        工作岗位: <%= loan.job %><br>
                        公司地址: <%= loan.company_add %><br>
                        月薪: <%= loan.salary %>
                      </div>
                      <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                  </div>
                </div>
              </div>

              <div class="timeline-footer">
                <!--<a class="btn btn-primary btn-xs">查看详情</a>-->
                <%= link_to '查看详情', background_manage_loan_path(loan), class: 'btn btn-primary btn-xs' %>
              </div>
            </div>
          </li>
          <!-- END timeline item -->
        </ul>
      </div>
    </div>
<% end %>

<!--<div class="paginate">-->
  <%= will_paginate @loans %>
<!--</div>-->