config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_for :admins

  authenticated :admin do
    root 'background/homes#home', as: :authenticated_root
  end

  get 'investments/index'

  get 'investments/edit'

  get 'investments/show'

  get 'investments/destroy'

  root 'static_pages#home'

  resources :users
  resources :loans
  resources :investments
  resources :contacts

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'help' => 'static_pages#help'
  get 'full_index' => 'loans#full_index'
  get 'search_loan' => 'loans#search'
  post 'search_loan' => 'loans#search'
  get 'add_money' => 'users#add_money'
  post 'pay' => 'users#pay'
  get 'pay' => 'users#pay'
  get 'return_loan' => 'users#return_loan'
  get 'return_pay' => 'users#return_pay'
  post 'return_pay' => 'users#return_pay'

  namespace :background do
    root 'homes#home'
    resources :checks
    resources :manage_loans
    resources :manage_investments
    resources :manage_users
    resources :manage_accounts
    resources :manage_contacts

    get 'search_user' => 'manage_users#search_user'
    post 'search_user' => 'manage_users#search_user'

    get 'high_search_user' => 'manage_users#search'
    post 'high_search_user' => 'manage_users#search'

    get 'high_search_loan' => 'manage_loans#search'
    post 'high_search_loan' => 'manage_loans#search'

    get 'high_search_loan_full' => 'manage_loans#search_full'
    post 'high_search_loan_full' => 'manage_loans#search_full'

    get 'loan_index_full' => 'manage_loans#index_full'

    get 'high_search_investment' => 'manage_investments#search'
    post 'high_search_investment' => 'manage_investments#search'

    get 'high_search_account' => 'manage_accounts#search'
    post 'high_search_account' => 'manage_accounts#search'

    patch 'reject_loan' => 'manage_loans#reject_loan'
    get 'reject_loan' => 'manage_loans#reject_loan'
  end

  get 'account_info' => 'users#account_info'

  get 'show_user' => 'loans#show_user'

  get 'update_head' => 'users#update_head'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  store_accessor :return_money, :mount, :date

  # has_many :active_relationships, class_name: 'Loan', foreign_key: 'follower_id'
  # has_many :passive_relationships, class_name: 'Loan', foreign_key: 'followed_id'
  # has_many :followers, through: :passive_relationships, source: :follower
  # has_many :following, through: :active_relationships, source: :followed

  # 充值用的虚拟属性
  attr_accessor :money

  # 搜索使用的虚拟属性
  attr_accessor :search_text
  attr_accessor :search_sex
  attr_accessor :search_time
  # validates :search_sex, inclusion: {in: %w(不限 男 女)}
  # validates :search_time, inclusion: {in: %w(不限 一周内 两周内 一个月内 三个月内)}

  # 用户头像
  has_attached_file :avatar, styles: {medium: '150x150>', thumb: '100x100>'}, default_url: ':style/missing.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :loans
  has_many :accounts

  has_and_belongs_to_many :investments

  validates :name, presence: true
  VALID_PHONE_NUMBER_REGEX = /1[3|5|7|8|][0-9]{9}/
  validates :phone_number, presence: true, length: {is: 11}, format: {with: VALID_PHONE_NUMBER_REGEX}
  # TODO sex应该只接受男, 女
  validates :sex, presence: true, inclusion: {in: %w(男 女)}
  # TODO 应该接受id_card的验证
  # validates :id_card, presence: true

  validates :reg_agree, acceptance: true

  # 返回制定字符串的哈希摘要
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # 搜索引擎
  searchable do
    text :name, :stored => true
    text :email, :id_card, :address
    text :phone_number
    string :sex
    time :created_at
    time :updated_at
    integer :id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # 账户资金信息
  def account_info
    @user = current_user
    @investmens = @user.investments
    @investmens.each do |investment|
      @user.invest_count += investment.mount
    end
  end

  def add_money
    @user = User.new
  end

  def return_loan
    @user = User.new
    @loan = Loan.find_by(id: params[:id])
  end

  def return_pay
    @user = current_user
    @loan = Loan.find_by(id: params[:user][:id_loan])
    money = params[:user][:money].to_f

    if @user.valid_capital < money
      flash.now[:warning] = '余额不足'
      render 'return_loan'
    else
      @user.valid_capital -= money
      @loan.already_pay += money
      @loan.return_money ||= []
      @loan.return_money << {mount: money, date: Time.now}

      if @user.save && @loan.save
        # 需要在投资者那里加上累积收益
        @loan.investments.each do |investment|
          investment.users.each do |user|
            user.profit_count += money * (investment.mount / @loan.mount)
            user.save
          end
        end

        flash.now[:success] = '还款成功'
      end
      render 'account_info'
    end
  end

  # 充值
  def pay
    @user = current_user
    money = @user.valid_capital + params[:user][:money].to_f
    @account = @user.accounts.build
    @account.mount = params[:user][:money].to_f
    if @user.update_attributes(valid_capital: money) && @account.save
      flash.now[:success] = '充值成功'
    end
    render 'account_info'
  end

  # 用户资料
  def show
    @user = current_user
    @city = ''
    unless @user.last_sign_in_ip.nil?
      ip_info = GeoIP.new('lib/GeoLiteCity.dat').city(@user.last_sign_in_ip)
      unless ip_info.nil?
        city_hash = ip_info.to_hash
        @city = city_hash[:city_name]
      end
    end
  end

  # 更新用户头像
  def update_head
    update_with_password
  end

  # 更新用户信息
  def update
    update_with_password
  end


  #更新用户头像的辅助方法

  def upload_image
    @user = current_user

    if @user.update_attributes(avatar_params)
      redirect_to @user, notice: '更新成功!'
    else
      redirect_to root_url
    end
  end

  # 更新用户不包含密码的信息
  def edit
    @user = current_user
  end

  # 更新用户的个人资料
  def update_info
    @user = current_user

    if @user.update_attributes(user_params)
      redirect_to @user, notice: '更新成功!'
    else
      redirect_to root_url
    end
  end

  private

  def update_with_password
    if !params[:current_password].blank? or !params[:password].blank? or !params[:password_confirmation].blank?
      super
    else
      params.delete(:current_password)
      if params[:user][:is_head] == 'true'
        self.upload_image
      else
        self.update_info
      end
    end
  end

  def avatar_params
    params.require(:user).permit(:avatar)
  end

  def user_params
    params.require(:user).permit(:email, :name, :phone_number, :address, :id_card, :sex)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account_info.html.erb
<% provide(:title, '账户资料') %>

<%= render 'shared/message' %>

<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 toppad">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">用户资料</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-3 col-lg-3 " align="center">
            <!--<img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive">-->
            <%= image_tag current_user.avatar.url(:medium), class: 'byemax' %>
            <%# form_for @user, html: {multipart: true} do |f| %>
            <%# f.file_field :avatar,  onchange: 'this.form.submit()' %>
            <!--<span class="btn btn-warning btn-file btn-sm upload-btn">上传头像<%# f.file_field :avatar, onChange: 'this.form.submit(); window.alert=null;' %></span>-->
            <!--<div class="upload-btn">-->
            <!--<%# f.submit '上传', class: 'btn btn-warning' %>-->
            <!--</div>-->
            <%# end %>
          </div>

          <div class="col-md-9 col-lg-9 ">
            <table class="table table-user-information">
              <tbody>
              <tr>
                <td>累积投资</td>
                <td><%= @user.invest_count %></td>
              </tr>
              <tr>
                <td>累积收益</td>
                <td><%= @user.profit_count %></td>
              </tr>
              <tr>
                <td>待收收益</td>
                <td><%= @user.profit_not_yet %></td>
              </tr>
              <tr>
                <td>冻结资金</td>
                <td><%= @user.frozen_capital %></td>
              </tr>
              <tr>
                <td>待收资金</td>
                <td><%= @user.capital_not_yet %></td>
              </tr>
              <tr>
                <td>可用资金</td>
                <td><%= @user.valid_capital %></td>
              </tr>
              <tr>
                <td>账户充值</td>
                <td><%= link_to '充值', add_money_path, class: 'btn btn-primary' %></td>
              </tr>

              <tr>
                <td></td>
                <td></td>
              </tr>

              </tbody>
            </table>

            <%# link_to '联系我', '#', class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
      <div class="panel-footer">

        <!--<a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>-->
                        <span class="">
                                  <%= link_to edit_user_path(current_user), data: {'original-title': '编辑我的资料', toggle: 'tooltip'}, type: 'button', class: 'btn btn-sm btn-warning' do %>
                                    <i class="glyphicon glyphicon-edit"></i>
                                  <% end %>
                          <span class="pull-right">
                            <%= social_share_button_tag "我是#{current_user.name}, 快来注册Money2Money吧~", url: root_url %>
                          </span>

                          <!--<a href="edit.html" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>-->
                          <!--<a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>-->
                        </span>
      </div>

    </div>
  </div>
</div>

<% unless current_user.investments.empty? %>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 toppad">
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">共投资 <strong><%= current_user.investments.size %></strong> 人</h3>
          </div>
          <div class="panel-body" id="investments-info">
            <table class="table table-striped table-hover">
              <tr>
                <th>投资邮箱</th>
                <th>投资姓名</th>
                <th>投资金额</th>
                <th>查看详情</th>
              </tr>
              <% current_user.investments.each do |investment| %>
                  <tr>
                    <td><%= investment.loan.user.email %></td>
                    <td><%= investment.loan.user.name %></td>
                    <td><%= investment.mount %></td>
                    <td><%= link_to '查看详情', loan_path(investment.loan) %></td>
                  </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
<% end %>

<%
  @loans = {}
  @loans[:passed] = current_user.loans.select {|loan| loan.passed == 'yes'}.sort{|x, y| y.updated_at <=> x.updated_at}
  @loans[:reject] = current_user.loans.select {|loan| loan.passed == 'failed'}.sort{|x, y| y.updated_at <=> x.updated_at}
  @loans[:fulled] = current_user.loans.select {|loan| loan.fulled}.sort{|x, y| y.updated_at <=> x.updated_at}
%>

<% unless @loans[:fulled].empty? %>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 toppad">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">共 <strong><%= @loans[:fulled].size %></strong> 个满标项目</h3>
          </div>
          <div class="panel-body" id="investments-info">
            <table class="table table-striped table-hover">
              <tr>
                <th>借款用途</th>
                <th>借款时间</th>
                <th>借款金额</th>
                <th>查看详情</th>
                <th>还款</th>
              </tr>
              <% @loans[:fulled].each do |loan| %>
                  <tr>
                    <td><%= loan.use %></td>
                    <td><%= get_time loan.created_at %></td>
                    <td><%= loan.mount %></td>
                    <td><%= link_to '查看详情', loan_path(loan) %></td>
                    <td><%= link_to '还款', return_loan_path(id: loan.id) %></td>
                  </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
<% end %>

<% unless @loans[:passed].empty? %>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 toppad">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">共借款 <strong><%= @loans[:passed].size %></strong> 次</h3>
          </div>
          <div class="panel-body" id="investments-info">
            <table class="table table-striped table-hover">
              <tr>
                <th>借款用途</th>
                <th>借款时间</th>
                <th>借款金额</th>
                <th>查看详情</th>
              </tr>
              <% @loans[:passed].each do |loan| %>
                  <tr>
                    <td><%= loan.use %></td>
                    <td><%= get_time loan.created_at %></td>
                    <td><%= loan.mount %></td>
                    <td><%= link_to '查看详情', loan_path(loan) %></td>
                  </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
<% end %>

<% unless @loans[:reject].empty? %>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 toppad">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title">借款被拒绝 <strong><%= @loans[:reject].size %></strong> 次</h3>
          </div>
          <div class="panel-body" id="investments-info">
            <table class="table table-striped table-hover">
              <tr>
                <th>借款用途</th>
                <th>借款时间</th>
                <th>借款金额</th>
                <th>查看详情</th>
              </tr>
              <% @loans[:reject].each do |loan| %>
                  <tr>
                    <td><%= loan.use %></td>
                    <td><%= get_time loan.created_at %></td>
                    <td><%= loan.mount %></td>
                    <td><%= link_to '查看详情', loan_path(loan) %></td>
                  </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/users/add_money.html.erb
<% provide(:title, '账户充值') %>

<%= render 'shared/message' %>

<!-- FORGOT PASSWORD FORM -->
<div class="text-center" style="padding:50px 0">
  <div class="logo">账户充值</div>
  <!-- Main Form -->
  <div class="login-form-1">
    <%= form_for @user, url: pay_path, html: {method: :post, class: 'text-left'} do |f| %>
        <div class="etc-login-form">
          <p>请输入充值金额</p>
        </div>
        <div class="login-form-main-message"></div>
        <div class="main-login-form">
          <div class="login-group">
            <div class="form-group field">
              <%= f.text_field :money, autofocus: true, class:'form-control', placeholder: '请输入充值金额' %>
            </div>
          </div>

          <div class="actions">
            <%= f.submit '充值', class: 'login-button' do %>
                <i class="fa fa-chevron-right"></i>
            <% end %>
          </div>

        </div>
    <% end %>
  </div>
  <!-- end:Main Form -->
</div>

app/views/users/edit.html.erb
<% provide(:title, '修改用户资料') %>

<!-- EDIT FORM -->
<div class="text-center" style="padding:50px 0">
  <div class="logo">修改您的资料</div>
  <!-- Main Form -->
  <div class="login-form-1">
    <%= form_for @user do |f| %>
        <%= f.hidden_field :is_head, value: 'false' %>
        <div class="login-form-main-message"></div>
        <div class="main-login-form">
          <div class="login-group">
            <div class="form-group field">
              <%= f.email_field :email, autofocus: true, placeholder: 'email', class: 'form-control', disabled: 'disabled' %>
            </div>

            <div class="form-group field">
              <%= f.text_field :name, class: 'form-control' %>
            </div>

            <div class="form-group field">
              <%= f.text_field :phone_number, autocomplete: "off", class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.text_field :address, class: 'form-control', placeholder: '家庭住址' %>
            </div>

            <div class="form-group">
              <%= f.text_field :id_card, class: 'form-control', placeholder: '身份证号码' %>
            </div>

            <div class="form-group login-group-checkbox">
              <!--<input type="radio" class="" id="male" placeholder="username">-->
              <%= f.radio_button :sex, '男', checked: true, id: 'user_sex_male' %>
              <%= f.label :sex_male, '男' %>

              <%= f.radio_button :sex, '女', id: 'user_sex_female' %>
              <%= f.label :sex_female, '女' %>
              <!--<label for="male">男</label>-->

              <!--<input type="radio" class="" id="female" placeholder="username">-->
              <!--<label for="female">女</label>-->
            </div>

          </div>
          <!--<button type="submit" class="login-button"><i class="fa fa-chevron-right"></i></button>-->
          <div class="actions">
            <%= f.submit '修改', class: 'login-button' do %>
                <i class="fa fa-chevron-right"></i>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
  <!-- end:Main Form -->
</div>

<%= link_to 'Back', :back %>

app/views/users/return_loan.html.erb
<% provide(:title, '还款') %>

<%= render 'shared/message' %>

<!-- FORGOT PASSWORD FORM -->
<div class="text-center" style="padding:50px 0">
  <div class="logo">还款</div>
  <!-- Main Form -->
  <div class="login-form-1">
    <%= form_for @user, url: return_pay_path, html: {method: :post, class: 'text-left'} do |f| %>
        <div class="etc-login-form">
          <p>共需还款 <%= @loan.should_return %></p>
          <p>已还 <%= @loan.already_pay %></p>
          <% if @loan.return_money.select { |n| n['date'] > Time.parse("#{Time.now.year}-#{Time.now.month}-1") }.count > 0 %>
              <p>您本月已还款</p>
          <% else %>
              <p>本月需要还款<%= (@loan.should_return / @loan.period).round(1) %></p>
          <% end %>
        </div>
        <div class="login-form-main-message"></div>
        <div class="main-login-form">
          <div class="login-group">
            <div class="form-group field">
              <%= f.text_field :money, autofocus: true, class: 'form-control', placeholder: '请输入还款金额' %>
              <%= f.hidden_field :id_loan, value: @loan.id %>
            </div>
          </div>

          <div class="actions">
            <%= f.submit '还款', class: 'login-button' do %>
                <i class="fa fa-chevron-right"></i>
            <% end %>
          </div>

        </div>
    <% end %>
  </div>
  <!-- end:Main Form -->
</div>

app/views/users/show.html.erb
<% provide(:title, '用户资料') %>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-2 toppad">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">用户资料</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-3 col-lg-3 " align="center">
            <!--<img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive">-->
            <%= image_tag current_user.avatar.url(:medium), class: 'byemax' %>
            <%= form_for @user, html: {multipart: true} do |f| %>
                <%# f.file_field :avatar,  onchange: 'this.form.submit()' %>
                <span class="btn btn-warning btn-file btn-sm upload-btn">上传头像<%= f.file_field :avatar, onChange: 'this.form.submit(); window.alert=null;' %></span>
                <%= f.hidden_field :is_head, value: 'true' %>
                <!--<div class="upload-btn">-->
                  <!--<%# f.submit '上传', class: 'btn btn-warning' %>-->
                <!--</div>-->
            <% end %>
          </div>

          <div class=" col-md-9 col-lg-9 ">
            <table class="table table-user-information">
              <tbody>
              <tr>
                <td>电子邮箱:</td>
                <td><%= @user.email %></td>
              </tr>
              <tr>
                <td>姓名:</td>
                <td><%= @user.name %></td>
              </tr>
              <tr>
                <td>联系电话:</td>
                <td><%= @user.phone_number %></td>
              </tr>
              <tr>
                <td>性别:</td>
                <td><%= @user.sex %></td>
              </tr>
              <tr>
                <td>家庭住址:</td>
                <td><%= @user.address %></td>
              </tr>
              <tr>
                <td>身份证:</td>
                <td><%= @user.id_card %></td>
              </tr>
              <tr>
                <td>登陆次数:</td>
                <td><%= @user.sign_in_count %></td>
              </tr>
              <tr>
                <td>当前IP:</td>
                <td><%= @user.current_sign_in_ip %></td>
              </tr>
              <tr>
                <td>上次登陆时间:</td>
                <td><%= get_time @user.last_sign_in_at %></td>
              </tr>
              <tr>
                <td>上次登陆IP地址:</td>
                <td><%= @user.last_sign_in_ip %>  <%= @city.to_s %></td>
              </tr>
              <tr>
                <td></td>
                <td></td>
              </tr>

              </tbody>
            </table>

            <%# link_to '联系我', '#', class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
      <div class="panel-footer">
        <%= mail_to "#{@user.email}", data: {'original-title': '给我发邮件', toggle: 'tooltip'}, type: 'button', class: 'btn btn-sm btn-primary' do %>
            <i class="glyphicon glyphicon-envelope"></i>
        <% end %>
        <!--<a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>-->
                        <span class="pull-right">
                                  <%= link_to edit_user_path, data: {'original-title': '编辑我的资料', toggle: 'tooltip'}, type: 'button', class: 'btn btn-sm btn-warning' do %>
                                    <i class="glyphicon glyphicon-edit"></i>
                                  <% end %>

                          <%= link_to registration_path(:user), data: {confirm: '确定注销?', commit: '注销', cancel: '取消', 'original-title': '注销用户', toggle: 'tooltip'}, method: :delete, type: 'button', class: 'btn btn-sm btn-danger' do %>
                          <i class="glyphicon glyphicon-remove"></i>
                          <% end %>


                          <!--<a href="edit.html" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>-->
                          <!--<a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>-->
                        </span>
      </div>

    </div>
  </div>
</div>